spring:
  application:
    name: external-api
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/check-mate?serverTimezone=UTC&characterEncoding=UTF-8
    username: yoowkim
    password: 12341234!@#$